### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jm594176** [adlnet/xapi-youtube#14]
I love the xapi youtube wrapper. I do have a question though. Have you ever heard of an issue where the "launched" statements are not being issued correctly? That is what is happening to us. If one person logs in and plays the video they get a launch statement. If they close out before completing then a completely differently person logging in as a different person only gets a "resumed" statement. I know this is weird but it is happening. I changed none of the code for the xapi wrapper. Thanks.
John M.

**Comment by creighton** [comment]
Hmm unsure. We'll look into it. Is the second person using the same browser/computer as the first person?

**Comment by jm594176** [comment]
Hi Tom,
No, it is a different person, different computer, different time, etc, and
yes, weird, but we see it consistently.
Like I said, the youtube wrapper is wonderful even with this anomaly. We
intend to use it for other things. If you are the original developer, thank
you for the time and effort that went into it.
Also, can you send me an email? I would like to contact you directly with a
link that you can see what I'm describing.
Thank you.
John M.
menken.john@gmail.com

**Comment by creighton** [comment]
@ty- was the original developer when he worked at ADL. He deserves the credit.

**Comment by creighton** [comment]
ISOTime in this case turns out to be "PT0.00S", but the playVideo function compares ISOTime to "PT0S" to determine if the statement should be "initialized" or "resumed". (https://github.com/adlnet/xapi-youtube/blob/master/src/xapi-youtube-statements.js#L83)


Update this to do a better compare.

**Comment by creighton** [comment]
my suggestion:

// parses the "PT0.00S" format, leaving just the number part
var makeNum = function(time) { return Number(time.slice(2, -1)); }

then update line 83ish to be
if (makeNum(ISOTime) === makeNum("PT0S") {..

or the PT0S side could just be 0..
